FROM node:8-alpine
WORKDIR /home/node/app
ADD . /home/node/app
RUN ["rm", "-rf", "node_modules", "package-lock.json"]
RUN ["npm", "install"]
RUN ["npm", "install", "-g", "serve"]
ENV NODE_ENV production
RUN ["npm", "run", "build"]
USER node
EXPOSE 8080
CMD ["serve", "-s", "dist", "-l", "8080"]
